# Generated by Django 2.1.7 on 2019-03-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
