# Generated by Django 2.1.7 on 2019-03-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0002_bopie_postupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bopie',
            name='postUpload',
            field=models.FileField(blank=True, null=True, upload_to='post_content'),
        ),
    ]
