# Generated by Django 2.1.7 on 2019-03-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0003_auto_20190309_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='bopie',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
