# Generated by Django 2.1.7 on 2019-03-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0004_bopie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bopie',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bopie',
            name='slug',
            field=models.SlugField(default='hello', max_length=250, unique=True),
        ),
    ]
