# Generated by Django 2.1.7 on 2019-03-14 01:14

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0004_bopie_is_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bopie',
            name='content',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
    ]
