# Generated by Django 2.1.7 on 2019-03-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0004_bopie_is_disabled'),
    ]

