# Generated by Django 2.1.7 on 2019-03-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0005_auto_20190308_0435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bopie',
            old_name='id',
            new_name='bopie_id',
        ),
        migrations.AlterField(
            model_name='bopie',
            name='slug',
            field=models.SlugField(default='hallo', max_length=250, unique=True),
        ),
    ]
