# Generated by Django 2.1.7 on 2019-03-14 03:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0008_remove_bopie_make_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='bopie',
            name='date_expiry',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Expiry Date'),
            preserve_default=False,
        ),
    ]
