# Generated by Django 2.1.7 on 2019-03-14 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0009_bopie_date_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bopie',
            name='date_expiry',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Expiry Date'),
        ),
    ]
