# Generated by Django 2.1.7 on 2019-03-15 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0010_auto_20190314_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bopie',
            name='date_expiry',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 3, 16, 23, 2, 4, 165898), null=True, verbose_name='Expiry Date'),
        ),
    ]
